global proc ktFindObjectsWithNoUVShells()
{
   string $ObjectsWithNoUVShells[];
   clear($ObjectsWithNoUVShells);
   $OldSel=`ls -type "mesh"`;
   
   for($e in $OldSel)
   {
     select $e;
     
     $shell_count=`polyEvaluate -uvShell`;
     if($shell_count[0]==0)
     {
     $sz=size($ObjectsWithNoUVShells);
     $ObjectsWithNoUVShells[$sz]=$e;
     }
   }
   
   select -cl;
   select $ObjectsWithNoUVShells; 
}
ktFindObjectsWithNoUVShells();
